"""add monthly budgets

How much to spend per category, every month or in one specific month.

Revision ID: 1a797959c945
Revises: 964c292cf175
Create Date: 2026-09-29 21:21:38.066770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a797959c945'
down_revision = '964c292cf175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_category'))

    op.drop_table('budgets')
    # ### end Alembic commands ###
