"""add accounts and account links on transactions

Bank accounts, cards and cash; each transaction can say which account it moves money from
(account_id) and, for a transfer between own accounts, where the money arrives (counter_account_id).

Revision ID: 600b086d0fab
Revises: a8306a4e5d00
Create Date: 2026-09-29 21:09:51.138001

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '600b086d0fab'
down_revision = 'a8306a4e5d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.Column('iban_tail', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('reconciled_on', sa.Date(), nullable=True),
    sa.Column('reconciled_balance', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('counter_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_counter_account_id'), ['counter_account_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_counter_account_id_accounts', 'accounts', ['counter_account_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_transactions_account_id_accounts', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_transactions_account_id_accounts', type_='foreignkey')
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_transactions_counter_account_id_accounts', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_counter_account_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))
        batch_op.drop_column('counter_account_id')
        batch_op.drop_column('account_id')

    op.drop_table('accounts')
    # ### end Alembic commands ###
