"""add missing transaction fields

Revision ID: 86c8730102a7
Revises: 845e23d97b47
Create Date: 2026-06-15 20:13:21.950277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86c8730102a7'
down_revision = '845e23d97b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('counterparty', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('recurrence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recurrence_end', sa.Date(), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('recurrence_end')
        batch_op.drop_column('recurrence')
        batch_op.drop_column('tags')
        batch_op.drop_column('counterparty')
        batch_op.drop_column('currency')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
