"""add wealth modules: holdings, debts, insurance policies, goals, documents, snapshots

The tables behind Portfolio, Debt, Insurance, Lifestyle → Goals, Documents and Snapshots,
which until now only showed their page layout.

Revision ID: 8f46aac702aa
Revises: e5f6a7b8c9d0
Create Date: 2026-09-29 17:53:41.294918

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8f46aac702aa'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('monthly_payment', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.Column('saved_amount', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=True),
    sa.Column('asset_class', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=38, scale=8), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=38, scale=6), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=38, scale=6), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('policy_number', sa.Text(), nullable=True),
    sa.Column('premium', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('coverage_limit', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('cash', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.Column('investments', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.Column('other_assets', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.Column('liabilities', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=38, scale=2), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('stored_name', sa.String(length=80), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_transaction_id'))

    op.drop_table('documents')
    op.drop_table('snapshots')
    op.drop_table('insurance_policies')
    op.drop_table('holdings')
    op.drop_table('goals')
    op.drop_table('debts')
    # ### end Alembic commands ###
