"""add exchange rates and amount in euro

Several currencies: rates to euro by date, and each transaction's value in euro (amount_base),
which totals and reports add up instead of the original amount.

Revision ID: 964c292cf175
Revises: 600b086d0fab
Create Date: 2026-09-29 21:15:59.930293

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '964c292cf175'
down_revision = '600b086d0fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('on', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'on')
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rates_currency'), ['currency'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_base', sa.Numeric(precision=38, scale=2), nullable=True))

    # ### end Alembic commands ###
    # No rates yet: every existing amount counts 1:1 (the Currencies page recomputes once rates are added)
    op.execute("UPDATE transactions SET amount_base = ABS(amount)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('amount_base')

    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_currency'))

    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
