"""link transactions to holdings and debts

What the money is for in the cash-flow statement: buying/selling an investment (investing) or
receiving/repaying a loan (financing).

Revision ID: f9a61d256bab
Revises: 1a797959c945
Create Date: 2026-09-29 21:42:13.449720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a61d256bab'
down_revision = '1a797959c945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holding_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('debt_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_debt_id'), ['debt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_holding_id'), ['holding_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_holding_id_holdings', 'holdings', ['holding_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_transactions_debt_id_debts', 'debts', ['debt_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_transactions_debt_id_debts', type_='foreignkey')
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_transactions_holding_id_holdings', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_holding_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_debt_id'))
        batch_op.drop_column('debt_id')
        batch_op.drop_column('holding_id')

    # ### end Alembic commands ###
